# EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

Orzal, Harvey Aaron E. 

2ECE - B

## NORMALIZATION PROBLEM
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

In [5]:
import numpy as np

X = np.random.rand(5, 5)
print("Original X:\n", X)

mean = X.mean()
std = X.std()
X_normalized = (X - mean) / std
print("\nNormalized X:\n", X_normalized)

np.save("X_normalized.npy", X_normalized)

Original X:
 [[0.23599807 0.91817067 0.02475937 0.81658665 0.0819693 ]
 [0.44413458 0.03084544 0.21198212 0.02769572 0.8518395 ]
 [0.18553525 0.94370393 0.12851866 0.96227993 0.58397868]
 [0.1154174  0.07063931 0.84575734 0.51963213 0.52861569]
 [0.72091317 0.33576815 0.96893953 0.83299079 0.12391846]]

Normalized X:
 [[-0.64626836  1.31815425 -1.25456324  1.02562721 -1.0898183 ]
 [-0.04690677 -1.23703745 -0.71542607 -1.24610756  1.12714328]
 [-0.79158396  1.39168128 -0.95577214  1.44517378  0.35579619]
 [-0.99349927 -1.12244477  1.10962875  0.17050025  0.19636979]
 [ 0.75012045 -0.35896484  1.46435115  1.07286549 -0.96901914]]


## DIVISIBLE BY 3 PROBLEM
Create the following 10 x 10 ndarray which are the square of the first 100 integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [7]:
import numpy as np

numbers = np.arange(1, 101)
squares = numbers**2 
A = squares.reshape(10, 10)
print("Matrix A:\n", A)

div_by_3 = A[A % 3 == 0]
print("\nDivisible by 3:\n", div_by_3)

Matrix A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
